name: project CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: User Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: node.js version
        run: nodejs -v
      - name: list
        run: ls -al
      - name: Install Dependencies
        run: npm ci
      - name: Project Build
        run: npm run build
      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: github-actions-practice
          heroku_email: somn45@gmail.com
